/**
 * AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
 * Generated by scripts/generate-factory-manifest.mjs
 *
 * Provides the list of agent-sdk factory modules for registration.
 */

export const MODULES = [] as const;

export type FactoryModuleSpec = (typeof MODULES)[number];
export type FactoryModuleLoader = () => Promise<Record<string, unknown>>;

export const MODULE_LOADERS: Record<FactoryModuleSpec, FactoryModuleLoader> = {

};

// Node-only factory modules - skipped at runtime in browser environments
export const NODE_ONLY_FACTORY_MODULES = new Set<FactoryModuleSpec>([

]);
